import HeroUiProvider from "@/context/heroUi-provider";
import QueryProvider from "@/context/query-provider";
import ReduxProvider from "@/context/redux-provider";
import { ThemeProvider } from "@/context/theme-provider";
import type { Metadata } from "next";
import "./globals.css";
import { Inter, Vazirmatn } from "next/font/google";

const vazirFont = Vazirmatn({
variable: "--font-Vazir",
subsets: ["arabic"],
});

const interFont = Inter({
variable: "--font-Inter",
subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${vazirFont.variable} ${interFont.variable}  antialiased`}
      >
        <ReduxProvider>
          <QueryProvider>
            <ThemeProvider>
              <HeroUiProvider>{children}</HeroUiProvider>
            </ThemeProvider>
          </QueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
